### ISSUE TITLE
Clear fields recalls census view

### ISSUE THREAD

**Issue by MichaelErichsen** [MichaelErichsen/VejbyGedcom#54]

**Comment by MichaelErichsen** [comment]
java.lang.NullPointerException: Cannot invoke "String.substring(int, int)" because "birthDate" is null
	at net.myerichsen.archivesearcher.views.CensusView.getInput(CensusView.java:650)
	at net.myerichsen.archivesearcher.views.CensusView.lambda$4(CensusView.java:687)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MichaelErichsen** [comment]
Issued in ArchiveSearcher::searchById at 

		try {
			populate(id, phonName, birthDate, deathDate);
		} catch (final SQLException e1) {
			((ArchiveSearcher) ((TabFolder) getParent()).getParent()).setMessage(e1.getMessage());
		}

**Comment by MichaelErichsen** [comment]
Issued by CensusView::clearFilters

**Comment by MichaelErichsen** [comment]
Statements removed
