### ISSUE TITLE
ProbatesView: PatternSyntaxExcecption when using an "[" as filter

### ISSUE THREAD

**Issue by MichaelErichsen** [MichaelErichsen/VejbyGedcom#61]
java.util.regex.PatternSyntaxException: Unclosed character class near index 4
.*[.*
    ^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.clazz(Pattern.java:2690)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2139)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at java.base/java.util.regex.Pattern.matches(Pattern.java:1174)
	at java.base/java.lang.String.matches(String.java:2842)
	at net.myerichsen.archivesearcher.filters.ProbateSourceFilter.select(ProbateSourceFilter.java:47)
	at org.eclipse.jface.viewers.ViewerFilter.filter(ViewerFilter.java:62)
	at org.eclipse.jface.viewers.StructuredViewer.getFilteredChildren(StructuredViewer.java:859)
	at org.eclipse.jface.viewers.StructuredViewer.getSortedChildren(StructuredViewer.java:1033)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalVirtualRefreshAll(AbstractTableViewer.java:645)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:620)
	at org.eclipse.jface.viewers.AbstractTableViewer.internalRefresh(AbstractTableViewer.java:610)
	at org.eclipse.jface.viewers.StructuredViewer.lambda$2(StructuredViewer.java:1461)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1400)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1361)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1461)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:526)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1420)
	at net.myerichsen.archivesearcher.views.ProbateView$2.keyReleased(ProbateView.java:103)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:178)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1067)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1094)
	at org.eclipse.swt.widgets.Text.sendKeyEvent(Text.java:1815)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.wmKeyUp(Widget.java:1835)
	at org.eclipse.swt.widgets.Control.WM_KEYUP(Control.java:5173)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4793)
	at org.eclipse.swt.widgets.Text.windowProc(Text.java:2681)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4938)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3624)
	at net.myerichsen.archivesearcher.views.ArchiveSearcher.main(ArchiveSearcher.java:97)

**Comment by MichaelErichsen** [comment]
Update column SOURCE in census tables EVENT and INDIVIDUAL to remove characters "[" and "]"

**Comment by MichaelErichsen** [comment]
Fixed using replace() in class ProbateSourceFilter
